### ISSUE TITLE
App Crashing when npm start

### ISSUE THREAD

**Issue by harwee** [prastut/bubble-frontend#53]
Here is the log

> /home/sriharshagangisetty/BubbleN/bubble-frontend/routes/bot/step-2/get-buzz.js:38
            async.map([...teamsObject], fetch, function(err, results) {
                       ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sriharshagangisetty/BubbleN/bubble-frontend/app.js:29:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by prastut** [comment]
@digi0ps @Tanay2112 @jeremyphilemon why is this error creeping up when it wasn't earlier. O.o

@harwee what is your node and npm version?

**Comment by harwee** [comment]
Node version: 4.2.6
Npm Version: 3.5.2

**Comment by prastut** [comment]
@harwee I dont have time to debug this atm. What I can suggest is install `nvm` and use the versions which I am using. 

`nvm` installation: https://github.com/creationix/nvm#install-script. Yeh install karle using the instructions provided. 

When you have installed `nvm` run `nvm install v6.10.0`. Then check your node version if its changed to v6.10.0.

**Comment by harwee** [comment]
Cool I will try it out!
